### ISSUE TITLE
About Flask

### ISSUE THREAD

**Issue by A-GHOSH-dev** [IEEE-WIE-VIT/WIE-WoC#136]
https://github.com/IEEE-WIE-VIT/WIE-WoC/tree/main/Web%20dev/Flask/About

**Comment by lem0n4id** [comment]
Hey, this has been completed in [PR 109](https://github.com/IEEE-WIE-VIT/WIE-WoC/pull/109).

Do you have any more content suggestions?

**Comment by A-GHOSH-dev** [comment]
Great
