### ISSUE TITLE
Steps to build a flask project

### ISSUE THREAD

**Issue by A-GHOSH-dev** [IEEE-WIE-VIT/WIE-WoC#138]
https://github.com/IEEE-WIE-VIT/WIE-WoC/tree/main/Web%20dev/Flask/How%20to%20build%20projects%20using%20this

**Comment by lem0n4id** [comment]
Hey, what all in needed in this? 

Just basics like `pip install flask` and `virtualenv` and setting up some **routes** should be enough, right?

**Comment by A-GHOSH-dev** [comment]
All steps involved in making your first Flask project. 

Include all commands. Usage of the commands should be well documented.

Folder Structure, explanation of the codes in the files created, etc.

**Comment by A-GHOSH-dev** [comment]
Would you like to get it assigned?

**Comment by lem0n4id** [comment]
Yes.

**Comment by A-GHOSH-dev** [comment]
Go ahead
