### ISSUE TITLE
your flask projects

### ISSUE THREAD

**Issue by A-GHOSH-dev** [IEEE-WIE-VIT/WIE-WoC#139]
https://github.com/IEEE-WIE-VIT/WIE-WoC/tree/main/Web%20dev/Flask/Projects

**Comment by prathimacode-hub** [comment]
Can I get this issue assigned to me? I would like to work on a Flask project. @A-GHOSH-dev

**Comment by A-GHOSH-dev** [comment]
You have one PR to be created. After you create that I can assign you this issue.

**Comment by A-GHOSH-dev** [comment]
I think you have one more PR now. After you finish that. Comment here. I will assign you this issue.

**Comment by prathimacode-hub** [comment]
Ok sure @A-GHOSH-dev

**Comment by A-GHOSH-dev** [comment]
Go ahead
