### ISSUE TITLE
Basics of DSA with Python

### ISSUE THREAD

**Issue by A-GHOSH-dev** [IEEE-WIE-VIT/WIE-WoC#163]
You can add some basic codes in Python like factorial, prime and perfect number , largest of three number, etc.

https://github.com/IEEE-WIE-VIT/WIE-WoC/tree/main/DSA%20Coding/Basics

**Comment by Aishwarya2003** [comment]
hi i will do it

**Comment by A-GHOSH-dev** [comment]
Go ahead
