### ISSUE TITLE
Some common recursion problems

### ISSUE THREAD

**Issue by A-GHOSH-dev** [IEEE-WIE-VIT/WIE-WoC#164]
Including codes of power , fibonaaci series using recursion, To print a string backwards using recursion.

https://github.com/IEEE-WIE-VIT/WIE-WoC/tree/main/DSA%20Coding/Recursion

**Comment by UrviSinghal28** [comment]
Hi can you please assign this to me

**Comment by Aishwarya2003** [comment]
Hi can I do it

**Comment by A-GHOSH-dev** [comment]
Hey @UrviSinghal28 

Someone else has already asked for this issue and I will assign it to her.

As given in the instructions in discord-
In the domain - DSA Coding- I won't be opening any issue. You can personally message me if you want to contribute any code. I will tell you how to go about it.

Whoever tells me first, I will create an issue and assign it to them.


If you are willing to contribute in anyother topic, please tell me. I will assign that to you.

**Comment by UrviSinghal28** [comment]
oh okay sorry didnt see that message

**Comment by A-GHOSH-dev** [comment]
@Aishwarya2003 please mention issue number in your PR description from next time.
