### ISSUE TITLE
Heart Disease Prediction

### ISSUE THREAD

**Issue by A-GHOSH-dev** [IEEE-WIE-VIT/WIE-WoC#179]
https://github.com/IEEE-WIE-VIT/WIE-WoC/tree/main/ML%20AI

**Comment by prathimacode-hub** [comment]
Can I get this issue assigned? @A-GHOSH-dev

**Comment by A-GHOSH-dev** [comment]
Go ahead

**Comment by prathimacode-hub** [comment]
PR has been created and I also requested for issues to be created so that I can get it assigned. If you could do so at the earliest, that would do the needful. @A-GHOSH-dev
